Add missing param to format_number XPath func
XPath functions are passed 4 args. However, the format-number XPath
function is defined to only accept 3 and raises a type error:
TypeError: format_number() takes 3 positional arguments but 4 were given