Fix footnotes GUI view
Adding XBRL footnotes view raises "AttributeError: 'LinkPrototype'
object has no attribute 'objectIndex'" because the linkRoleUris sorting
does not handle prototype objects which have no object index.